{% set name = "prometheus_flask_exporter" %}
{% set version = "0.18.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9a2af3d4ba014e3da6387b3b7cebaed291ccd6f474e240be13f50f8a5af671ca

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - flask
    - prometheus_client

test:
  imports:
    - prometheus_flask_exporter
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/rycus86/prometheus_flask_exporter
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Prometheus metrics exporter for Flask

extra:
  recipe-maintainers:
    - xhochy
