{% set name = "prometheus_flask_exporter" %}
{% set version = "0.14.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 794ff244a5316f5ac2b6c44972cc7d366b1829913cdc9572c044097ee62cc5a3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - flask
    - prometheus_client

test:
  imports:
    - prometheus_flask_exporter
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/rycus86/prometheus_flask_exporter
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Prometheus metrics exporter for Flask

extra:
  recipe-maintainers:
    - xhochy
